# Generated by Django 4.0.3 on 2022-03-28 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_partenaire_alter_post_publish_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 14, 48, 34, 814104, tzinfo=utc)),
        ),
    ]
