# Generated by Django 4.0.3 on 2022-03-28 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='photo',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='membres',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 15, 46, 57, 232894, tzinfo=utc)),
        ),
    ]
