# Generated by Django 4.0.3 on 2022-04-02 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_post_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 18, 20, 10, 175164, tzinfo=utc)),
        ),
    ]
