# Generated by Django 4.0.3 on 2022-04-09 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_username_profile_user_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 5, 28, 13, 980195, tzinfo=utc)),
        ),
    ]
