# Generated by Django 4.1.2 on 2024-01-19 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 22, 13, 47, 941721, tzinfo=datetime.timezone.utc)),
        ),
    ]
